version: '3'
volumes:
 pgdata:
services:
 gaurav:
  #image: python:3.7-alpine
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
   - ./mybot-master:/mybot-master
  ports:
   - 80:80
